name: CI

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install LLVM 8
      run: |
        sudo apt install build-essential
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo sh -c 'echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" >> /etc/apt/sources.list'
        sudo sh -c 'echo "deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" >> /etc/apt/sources.list'
        sudo apt update
        sudo apt install -y clang-8
    - name: Install cmake
      run: |
        sudo mkdir -p /opt/cmake
        wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2-Linux-x86_64.sh -O cmake.sh
        chmod +x cmake.sh
        sudo ./cmake.sh --prefix=/opt/cmake --skip-license
        rm cmake.sh
    - name: Install ninja
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
        unzip ninja-linux.zip
        sudo mv ninja /usr/bin/ninja
        rm ninja-linux.zip
    - name: Install Qt
      run: |
        sudo wget -nv https://github.com/benlau/qtci/raw/master/recipes/install-qt -O /usr/bin/install-qt
        sudo chmod +x /usr/bin/install-qt
        sudo wget -nv https://github.com/benlau/qtci/raw/master/bin/extract-qt-installer -O /usr/bin/extract-qt-installer
        sudo chmod +x /usr/bin/extract-qt-installer
        export QT_CI_PACKAGES=qt.qt5.5124.gcc_64
        export QT_CI_DOWNLOADER="wget -c -nv -N"
        sudo -E install-qt 5.12.4 /
    - name: Install Qt Creator
      run: |
        sudo mkdir -p /opt/qtcreator
        wget -nv http://download.qt.io/official_releases/qtcreator/4.9/4.9.2/qt-creator-opensource-linux-x86_64-4.9.2.run
        sudo extract-qt-installer qt-creator-opensource-linux-x86_64-4.9.2.run /opt/qtcreator
        rm qt-creator-opensource-linux-x86_64-4.9.2.run
    - name: Download Qt Creator source
      run: |
        wget -nv http://download.qt.io/official_releases/qtcreator/4.9/4.9.2/qt-creator-opensource-src-4.9.2.tar.xz
        tar xf qt-creator-opensource-src-4.9.2.tar.xz
        sudo mv qt-creator-opensource-src-4.9.2 /
        rm qt-creator-opensource-src-4.9.2.tar.xz
    - name: Configure
      run: |
        mkdir build
        cd build
        /opt/cmake/bin/cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_BUILD_TYPE=Release -DQTCREATOR_SRC="/qt-creator-opensource-src-4.9.2" -DQTCREATOR_BIN="/opt/qtcreator/bin/qtcreator" -DCMAKE_PREFIX_PATH=/Qt/5.12.4/gcc_64
    - name: Build
      run: |
        cd build
        ninja
    - name: Deploy
      run: |
        cd build
        ninja install

